apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjoge2EyeHBjMmhwYm1SaE9tZG9jRjlTV21wSGFrWkNUblpsYnpSRFVISmpjbXB5YzI5NFQyUTFjVkJ6T1VrMFVEQTBPRGM9fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
